export default [
    'Beaty Towers',
    'Broward Hall',
    'Buckman Hall',
    'Corry Village',
    'Cypress Hall',
    'Diamond Village',
    'East Hall',
    'Fletcher Hall',
    'Graham Hall',
    'Honors Village',
    'Hume Hall',
    'Infinity Hall',
    'Keys Complex',
    'Lakeside Complex',
    'Mallory Hall',
    'Murphree Hall',
    'North Hall',
    'Off-campus',
    'Rawlings Hall',
    'Reid Hall',
    'Riker Hall',
    'Simpson Hall',
    'Sledd Hall',
    'Springs Complex',
    'Tanglewood Village',
    'The Continuum',
    'Thomas Hall',
    'Tolbert Hall',
    'Trusler Hall',
    'Weaver Hall',
    'Yulee Hall',
];